### ISSUE TITLE
Feature Request [Amigo]: Audio Taps when you tap touchscreen

### ISSUE THREAD

**Issue by hugoender** [odudex/krux#8]
Would be awesome to have the speaker output a tap sound (similar to the tap sound an iPhone makes when you press keys on a keyboard) whenever you successfully touch a menu item on the screen or when you tap to move on to next page on pages with no menu items.

**Comment by odudex** [comment]
Interesting idea! I also thought about adding a beep when scanning QR codes and Tiny Seeds, so satisfying 😁. Could make it optional by configs.

**Comment by hugoender** [comment]
QR scan beep is a great idea!

**Comment by hugoender** [comment]
[tap.wav.txt](https://github.com/odudex/krux/files/11713775/tap.wav.txt)

Added tap.wav that we can use for the tap sound. Just remove the `.txt` from the end (had to add that for github to allow me to attach)

**Comment by hugoender** [comment]
[https://dl.sipeed.com/fileList/MAIX/HDK/Sipeed-Amigo/2970/Maix_Amigo_2970(Schematic).pdf](url)

Looking at that schematic, it seems like I2S2_SDO = 34, I2S2_WS = 18, and I2S2_CK = 21. The example code uses I2S0 and OUT_D1. I played around with changing I2S0 to I2S2 as well as I2S.DEVICE_0 to I2S.DEVICE_2 but have had no luck.

**Comment by hugoender** [comment]
Tried following this guide: https://wiki.sipeed.com/soft/maixpy/en/course/media/audio.html

First step states that `es8374.py` needs to be run if using Amigo (https://github.com/sipeed/MaixPy_scripts/blob/master/modules/others/es8374/es8374.py) so I downloaded that file and uncommented Amigo lines while commenting Cube lines. Apart from initializing and configuring the pins, this file seems to also start playback loop. Ran it but got the following error at the end with no sound:
```
[]
Traceback (most recent call last):
  File "<stdin>", line 832, in <module>
  File "<stdin>", line 757, in <module>
  File "<stdin>", line 216, in __init__
  File "<stdin>", line 275, in stop
  File "<stdin>", line 615, in setVoiceMute
  File "<stdin>", line 245, in _readReg
OSError: [Errno 116] ETIMEDOUT
>>> 
```

I used the `6.wav` file provided in the repo to ensure formatting of wav file is correct and remove that as a possible variable or cause of issue.

**Comment by hugoender** [comment]
Removed a bunch of extra code that I don't think has anything to do with playing a wav file and ended up with this:
```
# -*- coding: UTF-8 -*-

from machine import I2C

'''-----------------------------
1.测试 I2S 是否能够输出型号
2.测试 ES8374 是否初始化成功
3.测试 ES8374 是否配置正常
-----------------------------'''

if __name__ == "__main__":


    from fpioa_manager import *
    from Maix import GPIO, I2S, FFT

    import audio, time, image, lcd

    # amigo
    fm.register(13,fm.fpioa.I2S0_MCLK, force=True)
    fm.register(21,fm.fpioa.I2S0_SCLK, force=True)
    fm.register(18,fm.fpioa.I2S0_WS, force=True)
    fm.register(35,fm.fpioa.I2S0_IN_D0, force=True)
    fm.register(34,fm.fpioa.I2S0_OUT_D2, force=True)

    i2c = I2C(I2C.I2C3, freq=600*1000, sda=27, scl=24) # amigo

    fm.register(24,fm.fpioa.I2C1_SCLK, force=True)
    fm.register(27,fm.fpioa.I2C1_SDA, force=True)

    while True:

        try:
            print(i2c.scan())

            time.sleep_ms(2000)

            # init i2s(i2s0)
            i2s = I2S(I2S.DEVICE_0, pll2=262144000, mclk=31)

            # config i2s according to audio info # STANDARD_MODE LEFT_JUSTIFYING_MODE RIGHT_JUSTIFYING_MODE
            i2s.channel_config(I2S.CHANNEL_2, I2S.TRANSMITTER, resolution=I2S.RESOLUTION_16_BIT, cycles=I2S.SCLK_CYCLES_32, align_mode=I2S.STANDARD_MODE)

            # amigo
            fm.register(13,fm.fpioa.I2S0_MCLK, force=True)
            fm.register(21,fm.fpioa.I2S0_SCLK, force=True)
            fm.register(18,fm.fpioa.I2S0_WS, force=True)
            fm.register(35,fm.fpioa.I2S0_IN_D0, force=True)
            fm.register(34,fm.fpioa.I2S0_OUT_D2, force=True)
            

            for i in range(3):

                time.sleep_ms(10)

                # init audio
                #player = audio.Audio(path="/sd/res/sound/loop.wav")
                player = audio.Audio(path="/sd/6.wav")
                player.volume(100)

                # read audio info
                wav_info = player.play_process(i2s)
                # print("wav file head information: ", wav_info)
                i2s.set_sample_rate(wav_info[1])
                # print('loop to play audio')
                while True:
                    ret = player.play()
                    if ret == None:
                        # print("format error")
                        break
                    elif ret == 0:
                        break
                player.finish()

            del i2s, player

        finally:
            pass
  
```

Running this didn't result in any errors and it seems to be looping but I'm still not getting audio out. I'm wondering if my speaker is broken. If someone else can try the code above on their Amigo and let me know if they get sound, that'd be great. Remember that you need to place the [6.wav](https://github.com/sipeed/MaixPy_scripts/blob/master/multimedia/audio/6.wav) file in the SD card.

**Comment by NameStream** [comment]
su09-17-2023

ImportError: cannot import name MIC_ARRAY

MAix Amigo

(1.) Hi, there.

(2.) Using MAixPy IDE, receiving error code for MAix Amigo:

ImportError: cannot import name MIC_ARRAY

(3.) MAix AMIGO

(3a.) SP-MOD MicArray Module

(3b.) Connector:  10P 0.5mm FPC

(3c.) Sipeed MAix R6 + 1 Microphone Array Board

(3d.) Located inside the back of the developer board #2970, moved the switch to M1N instead of STM.
* * * * * * * * {  By the way, STM yields same results. } * * * * * * * *

(3e.) MAixPy IDE:  Tools > Select Board > Sipeed Maixduino

(3f.) Will only run the code for “helloworld.py”, although the LCD image orientation is misaligned, upside down; the picture is smaller than the LCD screen; but image has mostly clear resolution without any noticeable lag, latency, delay.

(3g.) Receiving “ImportError:  cannot import name MIC_ARRAY”
when attempting to run the code for:

ROUTINE Sound Source Localization

https://wiki.sipeed.com/soft/maixpy/en/develop_kit_board/module_microphone.html

*******and*******also*******for*******

AirPocket Soundman’s Sound Localizer
https://github.com/airpocket-soundman/SoundVisualizer/blob/main/src/mic_array_en_ver204.py

(3h.) Pin assignments used for MAix AMIGO

LED_CLK_GPIOHS28…….23

LED_DAT_GPIOHS27…….20

DAT 0…………….......……12

DAT 1……………..…..…….…9

DAT 2………………..…...……31

DAT 3………….……..……...7

WS……………..…....…..……19

BCK_SCK……...…..…………17

(4.) Would you list the correct pin assignments for the:

(4a.) MAix Amigo #2970 in the M1n position

(4b.) MAix Amigo #2970 in the STM position

(5.) Thanks.

(6.) Toodles!

**Comment by tadeubas** [comment]
I've noticed the official repo of MaixPy fixed something related to the MIC_ARRAY pins here:

https://github.com/tadeubas/MaixPy/compare/master...sipeed:MaixPy:master#diff-61e8c49091a86dbb13ce9b024b8a8bbdce77417ade3dee4241528aac93ff5637R243

**Comment by LopesRs** [comment]
Hello, about Krux Android. I have a problem with my Android, it doesn’t read the SD card, but the device reads normally.
